language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=kinto-master
    - TOX_ENV=flake8
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
matrix:
  include:
    - go: 1.5
      language: go
      env:
        - TOX_ENV=functional
      install:
        - pip install --user virtualenv tox
        - make install
        - make run-autograph &
        - make run-kinto &
    - go: 1.5
      language: go
      env:
        - TOX_ENV=functional
          WITH=kinto-master
      install:
        - pip install --user virtualenv tox
        - make install
        - .venv/bin/pip install -U https://github.com/Kinto/kinto/zipball/master
        - make run-autograph &
        - make run-kinto &
    - python: 3.5
      env:
        - TOX_ENV=py35
